version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_db
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC                  # Force container system time to UTC
      - PGTZ=UTC                # Force Postgres internal timezone to UTC
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"